#!/bin/bash
src_str=(I am oldboy teacher welcome to oldboy traning class)
num=${#src_str[*]}
#echo "$src_str"
#echo "$num"
i=0
for((i=0;i<$num;i++))
  do
    if((${#src_str[$i]}<=6))
    then
      echo "${src_str[i]}"
    fi
  done
